package src;

public enum NavMeshMapTypes {
    COST,
    BENEFIT,
    ENEMY_KNIGHTS,
    NON_FRIENDLY_PLACES_TO_BUILD,
    NON_TOWER_PLACES_TO_BUILD,
    TOWER_PROTECTION,
    ENEMY_TOWER_RANGE,
    BLOCKER
}
